### PR TITLE
#34: Disabling auto-redirect-handling

### PR DESCRIPTION
**Pull request by lefloh**

### CODE REVIEW

**Comment by thoop** [comment]
:+1: 

@greengerong can you merge this?

**Comment by greengerong** [comment]
@lefloh Thanks

**Comment by lefloh** [comment]
You're welcome. Do you already know when you'll release next time?

**Comment by greengerong** [comment]
@lefloh At present, I am in a public holiday. Maybe, next week will be better. I will release it, as soon as possible.  @lefloh

**Comment by lefloh** [comment]
@greengerong Thank you so much and enjoy your holiday!

**Comment by greengerong** [comment]
@lefloh New version [1.6.4](https://oss.sonatype.org/index.html#nexus-search;quick~com.github.greengerong) is ready.  Thanks.

**Comment by thoop** [comment]
Thanks @greengerong !!

**Comment by lefloh** [comment]
Thanks!

**Pull request merged**
