### PR TITLE
Https config for issue #44

### PR DESCRIPTION
**Pull request by kgujral**

### CODE REVIEW

**Comment by kgujral** [comment]
I have created this new PR. Finally all checks have passed :)

**Comment by kgujral** [comment]
Everything looks good. Please merge this one whenever you have the time.

**Comment by thoop** [comment]
Sorry, I was tagging @greengerong so that he would get a notification and see this. @greengerong can you merge this? He's the one that has merge access.

**Comment by kgujral** [comment]
Ohh sorry I misread it! My Bad

**Comment by greengerong** [comment]
Thanks

**Comment by thoop** [comment]
@greengerong Thank you!

**Pull request merged**
