### PR TITLE
Add yandex to a list of known crawler user agents

### PR DESCRIPTION
**Pull request by mvaitkus**

### CODE REVIEW

**Comment by thoop** [comment]
Yandex supports the escaped fragment crawling protocol so you might get penalized for cloaking if you check yandex by their user agent. Is there a reason you need to check for the yandex user agent?

**Comment by mvaitkus** [comment]
Yes, yandex crawler does issue a second request with escaped fragment query parameter.

However I am not entirely sure if it respects the response status of the second request (with escaped fragment param). We have an issue with non existing pages and all other crawlers almost stopped hitting them, except yandex. This is when I noticed that we handle yandex differently - all other bots go to prerender immediately and yandex has to do two requests, one for js version which returns a 200 response code and second one with escaped fragment param which is handled by prerender and returns a 404.

**Comment by thoop** [comment]
If they are following the escaped fragment crawling protocol then they should honor the 404. Are you returning a 404 using the `prerender-status-code` meta tag? Google and Bing don't have any issue with that and they support the escaped fragment crawling protocol.

**Comment by mvaitkus** [comment]
I got response from yandex support and it seems that on situations, when normal call returns a 200 and one with escaped fragment returns 404, they will come back and try to index it later, which is what I would like to avoid. These pages do not exist any more and I want it to be registered as non existing as soon as possible, therefore yandex is already added to the crawler list in my service through configuration.

I have actually included yandex to the list in this PR, because most of the other search engines where there and I thought that someone forgot to include it. Are there yandex bot differences that would require to handle it differently from google, bing, etc.?

**Comment by thoop** [comment]
It sounds like this is the only difference. If you check yandex by user agent then you risk being penalized for cloaking. I'd ask yandex support about that since they obviously are not following the escaped fragment crawling protocol correctly. Google and Bing do not have that issue. If Google or Bing see a 404 from the escaped fragment URL then they will take that as the real response code.

**Comment by greengerong** [comment]
yandex is supported.

**Pull request closed without merging**
