### PR TITLE
Https config for issue #44

### PR DESCRIPTION
**Pull request by kgujral**

### CODE REVIEW

**Comment by thoop** [comment]
Thanks @kgujral! Looks great. I'm not sure why the CI failed though. Did you change anything there? Can you try running that again? Seems like it was just your readme change that caused it to fail.

**Comment by kgujral** [comment]
No I did not change anything that might make the CI fail. I read the CI logs seems like an issue with the CI rather than the code itself.

```
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
The command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " failed 3 times.
```

**Comment by thoop** [comment]
@greengerong any idea why this might have failed? Can you force a retry? And if it looks good, can you merge this PR? It adds a nice protocol config option :)

**Comment by kgujral** [comment]
Created new PR #48

**Pull request closed without merging**
