### PR TITLE
fixes whitelist issue 46

### PR DESCRIPTION
**Pull request by codetothepoint**
Fixes the logic to correctly honor whitelists, and updates respective test coverage.

see also: https://github.com/greengerong/prerender-java/issues/46

### CODE REVIEW

**Comment by greengerong** [comment]
Thanks. For normal case,  even though the url is in white list, but we still need to check user agent. For your case is a special case, I think you can give a switch to enable check user-agent or not.

Do you think is it ok?

**Comment by codetothepoint** [comment]
That makes perfect sense. I like the idea of adding a switch to check
User-Agent. I will update my pull request. Thank you!

- Scott

**Comment by codetothepoint** [comment]
@greengerong: I appreciate your feedback, and agree with your suggestion.  I have updated the pull request to support a new config parameter called `ignoreUserAgent`.  Let me know what you think!  Thank you.

- Scott

**Comment by thoop** [comment]
I just commented on your #46 issue too, but wanted to add my same point here for visibility:

We don't recommend serving Prerendered pages to users when using our prerendering service since we remove javascript tags to prevent crawlers from trying to execute the javascript and clearing out the static html that has been prerendered.

So if that's the reason for ignoring the user agent check, there might be issues that prevent this from working as you expect for your users.

**Comment by greengerong** [comment]
@codetothepoint The code have conflicting.

**Comment by thoop** [comment]
Does this code fix any whitelist issue anymore? Looking into the changes, it just adds an option to ignore the user agent check, which would cause prerendered pages to be returned to all users. We don't recommend serving Prerender.io pages to users since the `<script>` tags are removed from all prerendered pages and your javascript would no longer work for users.

**Pull request closed without merging**
